### ISSUE TITLE
Version 0.0.9

### ISSUE THREAD

**Issue by kreezxil** [cyanobacterium/PowerAdvantageAPI#1]
"Changed config for demo=false and from NORMAL to TECH_PROGRESSION on dedicated server b1398; it crashed at startup."
server crash report: http://pastebin.com/gTBKfjN4
server fml latest: http://pastebin.com/9TnKZDx3

Also the conveyor recipe is missing which is why I was tweaking the config.

I put it back to NORMAL and it worked also demo is still false; still can't get that basic conveyor recipe.

My config:

```
# Configuration file

options {
    B:demo=false

    # NORMAL, APOCALYPTIC, or TECH_PROGRESSION. 
    # Sets the style of recipes used in your game. 
    # In NORMAL mode, everything needed is craftable from vanilla items and the machines are 
    # available pretty much as soon as the player returns from their first mining expedition. 
    # In APOCALYPTIC mode, some important items are not craftable, but can be found in 
    # treasure chests, requiring the players to pillage for their machines. 
    # In TECH_PROGRESSION mode, important items are very complicated to craft using vanilla 
    # items, but are easy to duplicate once they are made. This gives the players a sense of 
    # invention and rising throught the ages from stone-age to space-age. [default: NORMAL]
    S:recipe_mode=NORMAL

    # Controls the rarity of items from this mod being found in treasure chests relative to 
    # the frequency of other chest loot items. Set to 0 to disable metal ingots from 
    # appearing in treasure chests. [range: 0.0 ~ 1000.0, default: 0.5]
    S:treasure_chest_loot_factor=0.5
}


```

**Comment by DrPlantabyte** [comment]
Are you using the latest version (v1.3.0) of BaseMetals?

**Comment by kreezxil** [comment]
Yes.

**Comment by DrPlantabyte** [comment]
Your crash report says 

```
basemetals{1.2.3} [Base Metals] (basemetals-1.2.3.jar) Unloaded->Constructed->Pre-initialized->Initialized
```

If that's the version being used, then that would explain the error. I'll check to see if I uploaded the wrong version of Base Metals and do another test on my dedicated server.

**Comment by kreezxil** [comment]
That would explain it. The filenames end in 1.3.0

-----Original Message-----

**Comment by DrPlantabyte** [comment]
I downloaded Base Metals 1.3.0 from the [github page](https://github.com/cyanobacterium/BaseMetals/releases/tag/v1.3.0) that was linked in the [forum post](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2352456-drcyanos-base-metals) and still did not get the crash that you report and it reported version 1.3.0 in the log. Go to http://onlinemd5.com/ and check the MD5 hash for your Base Metals .jar file. It should be **82D3669BB6A75770D31357DB1D408CDA** . IF you get a different MD5 hash code, then you have the wrong file and should re-download it.

**Comment by kreezxil** [comment]
Well this is some weird stuff.

I'm on the github page that forum post takes me too at
https://github.com/cyanobacterium/BaseMetals/releases/tag/v1.3.0 and that
file when put into onlinemd5.com as you suggest generated the MD5
has 82D3669BB6A75770D31357DB1D408CDA. So in this case redownloading it
won't work for me.

**Comment by kreezxil** [comment]
Weird weird weird, for shits and grins I deleted and the reinstalled basemetals and the poweradvantage jars on both sides. And now it works.

**Comment by kreezxil** [comment]
The only things that have changed since the initial report of the crash and now is I've found 2 mods in my mod pack that were messing with basic core recipes of Mojang and removed them, and instead of b1398, we're now at b1404.

**Comment by DrPlantabyte** [comment]
I'm glad you managed to fix it. :)
