### ISSUE TITLE
Wrenching things upside-down does not always work.

### ISSUE THREAD

**Issue by 7eggert** [cyanobacterium/PowerAdvantageAPI#14]
1) Place hopper facing downwards, or place conveyor facing up/down
2) use wrench on hopper/conveyor

Expected: Hopper cycles NSWE\* and down, conveyor NSWE and up/down

Happens: Hoper cycles NSWE only, conveyor can turn from facing down to up once, then will also only cycle through NSWE.

(Other items, e.g. the Hopper Ducts are wrenchable as expected.
- North, South, …

**Comment by DrPlantabyte** [comment]
In Minecraft 1.9, I switched to using Vanilla Minecraft's rotate function, which apparently doesn't do vertical. The blocks that Minecraft doesn't know how to rotate do blockstate cycling (hence the 6-directions available on Hopper Ducts).

For vertically aligned blocks, do you prefer that it cycle through all blockstates or toggle between UP and DOWN?

**Comment by 7eggert** [comment]
I'd prefer cycling through all directions. Sometimes you can't place the blocks correctly so this might be required.

(BTW, is it possible to flip double-chests?)

**Comment by DrPlantabyte** [comment]
Old behavior restored in v2.1.1
