### ISSUE TITLE
Chain of filtering conveyors acts like overflow conveyor

### ISSUE THREAD

**Issue by 7eggert** [cyanobacterium/PowerAdvantageAPI#16]
When the output of a filtering conveyor is a chest and that chest is full, the conveyor will stop forwarding items. However if the output is an oven, a stack of conveyors will pass on items:

On an infinite electric power source, place an oven. On top of that, place a furnace filter. On top of that, place a food filter (order of filters does not matter). Place chests next to the conveyors. Fill the input side chests with raw porkchop.

The bottom conveyor will output only into the oven. (desired).
The top conveyor will pass on it's input to the output chest.

**Comment by 7eggert** [comment]
Possibly related: When I have a row of coal->steam generators that makes a 90 degree turn, filled by overflow conveyors on top, the conveyor on the turn needs to face in the direction of the other generators/conveyors. The next conveyor would not pull out the blocked coals.

**Comment by DrPlantabyte** [comment]
That would be a little complicated to implement. I use vanilla hoppers to act as a buffer in these situations.

**Comment by 7eggert** [comment]
Maybe I have an idea if you point me to the corresponding code.

**Comment by 7eggert** [comment]
![2016-06-04_05 11 21](https://cloud.githubusercontent.com/assets/924567/15797308/426e49f4-2a13-11e6-9734-661f71595332.png)

I tested the normal conveyor after that filtering conveyor, too, it didn't pull out filtered items. That was due to having another filtering conveyor below, a different bug.

**Comment by DrPlantabyte** [comment]
I found the source of the overflow bug. It will be fixed in the next version. I do not plan to add 90 degree turning filters in the near future, so you may have to spread your builds out a little bit to use a normal conveyor on each turn.

**Comment by DrPlantabyte** [comment]
By the way, thank you for being a rigorous tester and reporting back the bugs, 7eggert.

**Comment by 7eggert** [comment]
Miscommunication: The conveyot on the edge needs to point in the new direction, expecting the next conveyor to just pull the item does not work. I realize now that this is due to the item being filtered down so it should not be pulled. The next conveyor can't be expected to know this special case for overflow conveyors.

90°-conveyors aren't necessary, output-only-conveyors  / closed input side might look nicer (and not mis-pull items) but dont-do-that-then is OK.
