### ISSUE TITLE
With Biomes of Plenty: crash on picking up overflow conveyor

### ISSUE THREAD

**Issue by 7eggert** [cyanobacterium/PowerAdvantageAPI#18]
I don't know if this is a PA bug at all. I'll also report it on BiomesOPlenty

java.lang.IllegalArgumentException: Cannot set property PropertyDirection{name=facing, clazz=class net.minecraft.util.EnumFacing, values=[north, south, west, east]} to down on block poweradvantage:item_filter_overflow, it is not an allowed value
    at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177226_a(BlockStateContainer.java:208)
    at cyano.poweradvantage.machines.conveyors.BlockConveyorFilter.func_176203_a(BlockConveyorFilter.java:85)
    at biomesoplenty.common.handler.AchievementEventHandler.onItemPickup(AchievementEventHandler.java:58)

[report.txt](https://github.com/cyanobacterium/PowerAdvantageAPI/files/261995/report.txt)

**Comment by DrPlantabyte** [comment]
Weird. When does this bug occur? Something is trying to rotate a conveyor to face down, but they can't do that.

**Comment by 7eggert** [comment]
It was on picking it up.

I referenced the line of code in the other bug report. Sorry for not having the steps-to-reproduce here, I'll copy/paste them immediately:

Steps to reproduce:
1) place overflow conveyor
2) use pickaxe on overflow conveyor
3) pick up item (if not done automatically)

**Comment by DrPlantabyte** [comment]
Looks like some rockiness as the block meta-data number if finally being phased out from Minecraft. Next release will have a work-around.
