### ISSUE TITLE
Copy/paste error in programm code

### ISSUE THREAD

**Issue by 7eggert** [cyanobacterium/PowerAdvantageAPI#20]
poweradvantage/api/PoweredEntity.java  :
166     private final int getTickOffset(){
167         BlockPos coord = this.getPos();
168         int x = coord.getX();
169         int y = coord.getX();
170         int z = coord.getX();
171         return ((z & 1) << 2) | ((x & 1) << 1) | ((y & 1) );

Obviously this should be getY() / getZ()

**Comment by DrPlantabyte** [comment]
Thanks for the catch. I will fix it now
