### ISSUE TITLE
Graphics bug when connecting pipes to other mods [1.8.9]

### ISSUE THREAD

**Issue by ghost** [cyanobacterium/PowerAdvantageAPI#22]
I'm getting a bug where the graphics on the pipes turn into the purple and black squares after I break them. I can still pick them up and place them afterwards without a problem. No errors in the console.

I notice that this happens when I CONNECT them to other mod pipes, machines and inventory such as Buildcraft, ExtraUtilities and Advanced Generators. This doesn't happen when I place pipes that are NOT connected to other mods.

[Example Picture](https://postimg.org/image/xif6ebfwr/)

**Comment by DrPlantabyte** [comment]
Do you get the same results when you are breaking the pipe with a tool vs without holding an item?

**Comment by ghost** [comment]
It only seems to do it when I break it with an item. It can be any item. I tried sever different items in my hand like leather, torches, crafting table, Dark Matter Pickaxes, and a Red Matter Sword. It breaks into a normal pipe when I use my hand.

**Comment by DrPlantabyte** [comment]
Should be fixed in version 1.5.6

**Comment by ghost** [comment]
Thank you! You are super awesome!
