### ISSUE TITLE
Potential desync condition in PoweredEntity

### ISSUE THREAD

**Issue by OhiraKyou** [cyanobacterium/PowerAdvantageAPI#25]
I was just poking around the base entity classes in Power Advantage (because they contain code that pretty much any entity would need) when I came across [a potentially dangerous bit in PoweredEntity](https://github.com/cyanobacterium/PowerAdvantageAPI/blob/master/src/main/java/cyano/poweradvantage/api/PoweredEntity.java#L96).

In a multiplayer scenario in which one player is keeping a machine's chunk loaded while another player is greater than 256 blocks away, if the distant player were to then enter that 256 block range, wouldn't they fail to receive the packet? Unless I'm misunderstanding something, that could lead to some strange desync symptoms until the next sync.

Incidentally, I hope you don't mind me cherry picking code from those classes as I don't yet need the "power" part of Power Advantage and am therefore not yet committed to a dependency on it.

**Comment by jriwanek** [comment]
As long as your code is LGPL compatible and credit for the code is given, I'd say that was fine, @cyanobacterium will likely comment on the rest.

**Comment by OhiraKyou** [comment]
While creating my own turret, I've found that this function does, indeed, cause players 16 blocks or more away from the entity to not receive visual updates.

When the player is more than 16 blocks away, this causes the laser turret from Electric Advantage to continue rotating in its idle animation while dealing damage to mobs with no visual cues. And, if the turret was locked on when the player moved to over 16 blocks away, the turret remains facing the direction of its last known target, even when the player steps back into the 16 block radius.

As a fix for my own turret, I've elected to simply send the packet to all players. It may be a bit of a heavy approach, but because my turrets have more visual cues, I'd rather they not get out of sync for any reason. Here's the code I threw together:

``` java
protected final void sync(){
    this.markDirty();
    Packet packet = this.getUpdatePacket();
    if (packet == null) return;

    for (EntityPlayer player : getWorld().playerEntities){
        if (player instanceof EntityPlayerMP) {
            EntityPlayerMP playerMP = (EntityPlayerMP)player;
            playerMP.connection.sendPacket(packet);
        }
    }
}
```

**Comment by OhiraKyou** [comment]
Just now also discovered why the Electric Advantage turret (and mine) doesn't become active on world load. getUpdateTag() should be used to feed getUpdatePacket with the update's NBT tag. getUpdateTag(), rather than the packet, is automatically sent to players loading a chunk.

**Comment by DrPlantabyte** [comment]
Good job!
Sadly, I don't have time to work on Minecraft mods anymore, so I'm just doing a final round of updates to MC 1.10.2 and then I'm done. However, all of my Minecraft mods are open to being maintained or reinvented by others.

I consider it a compliment when someone copies my (open-source) code. Take whatever you wish.
