### ISSUE TITLE
Server Crash Reports

### ISSUE THREAD

**Issue by hero887** [cyanobacterium/PowerAdvantageAPI#3]
I can run Power Advantage for my client side using Multi-MC but when I go to run my server with the same mods installed - Power Advantage 1.3.5 - it does not work. It says it's missing Power Advantage. Please note that I am running a 1.8-11.14.4.1563 Forge server.

This is the crash report for 1.3.5: http://pastebin.com/cir8L6m5

Then I tried updating to the latest release (1.4.3) (I did notice the note of "upgraded to 1.8.9" but I thought I'd try it anyway and see if it was backwards compatible) but as you may have already guessed, it crashed saying it was the wrong version of forge and/or Minecraft version.. See here: http://pastebin.com/AhujRYay

Do you have any advice as to why 1.3.5 wouldn't work? And if possible, can you back port the latest release to 1.8? Or perhaps make the newest release compatible for 1.8 too? I am stuck at 1.8 due to the required mods that are absolutely necessary for my modpack. Otherwise, I would update to 1.8.9 since it is the best and the future.

I really greatly appreciate any help or guidance here! Thank you!

**Comment by DrPlantabyte** [comment]
The problem is that your java version on the server is java 7. Upgrade to java 8 and it will work.
