### ISSUE TITLE
Request for 1.8 Backport

### ISSUE THREAD

**Issue by hero887** [cyanobacterium/PowerAdvantageAPI#4]
The 1.4.0 update was huge with the new oil and fluid API added. I was really hoping to have that for MC ver. 1.8 if possible. I know that 1.8 is on it's dying breath and 1.8.9 is the new and improved, but because of key mods I need, I would like to request that the latest Pwr. Adv. would be made compatible with forge-1.8-11.14.4.1563.

You don't have to grant it, but something of interest to you may be the new unreleased mod called ARKCraft. It makes the PC game ARK: Survival Evolved come to MC. Because in that PC game there is crude oil and gasoline, your mod seems to be the perfect fit for integration. I am apart of the dev team (although I'm no coder) and I have mentioned your API to them. There is some good interest. But the mod is only for 1.8 at this time. I'm sure they will update, but it may take months. The main thing is the ability to have that fluid API and oil world gen for 1.8. I can get you in touch with the coders if you would like to talk to them more. For starters you can join my Discord chat where a couple of them are as well: https://discord.gg/0cQ7fahdZUZZDFyt

You will want to talk to Lewis_McReu or BubbleTrouble. On a side note, many of the JurassiCraft guys are on the ARK team too - if you ever wanted to connect with them. I'm confident they would welcome your help and lend theirs too as a team.

All in all, I see your API integrating perfect for the next stages of ARKCraft's development as they look to code the machines and so on. I hope you may consider the back port or perhaps give guidance to the mod dev team of ARKCraft to do so for that mod specifically. Assuming this is open source, which I was thinking it was. You can message me back here or reach me on the Discord chat. My username is the same there too.

Great work, I really love your mods!

**Comment by DrPlantabyte** [comment]
Sure, I can make a back-port for you, but let me finish updating Electric Advantage first.

In the mean-time, you can just include the Power Advantage 1.4.3 jar in the ARK project and use that since the back-port process won't change any of the API methods (only a few internal rendering methods need to change between 1.8.0 and 1.8.9). Feel free to contact me for questions and advice (send me a private message on MinecraftForum.net so I can give you more contact info).

Thank-you for your appreciation of my mods. Good luck!

**Comment by DrPlantabyte** [comment]
Here you go, the backport is finished:
https://github.com/cyanobacterium/PowerAdvantageAPI/releases/tag/v1.4.4-backport
