### ISSUE TITLE
Backport Crashes :(

### ISSUE THREAD

**Issue by hero887** [cyanobacterium/PowerAdvantageAPI#5]
Started trying out the new pre-release back port of Power Advantage but ran into some crashes sadly.

Server Crash:
http://pastebin.com/bBuAjYay

Client Crash:
http://pastebin.com/s8viLaP1

**Comment by hero887** [comment]
Note that I have other mods installed along with your mods that may have caused that crash report. Perhaps the issues is the fact I have Electric and Steam Advantage too?

**Comment by DrPlantabyte** [comment]
I'm not having any trouble at all, even with Electric Advantage 1.0.5 and Steam Advantage 1.4.0.

That error looks like you are either running the API jar (which is not re-obfuscated) or are trying to run with the non-API jar in the IDE (running in the IDE uses de-obfuscated Minecraft-Forge).

**Comment by hero887** [comment]
Ah. Stupid me. I downloaded the API and tried running that. Obviously that would make sense why it crashed.
