### ISSUE TITLE
Null pointer exception after trapping myself with a chest?

### ISSUE THREAD

**Issue by dreness** [cyanobacterium/PowerAdvantageAPI#7]
[crash-2016-03-22_20.54.42-server.txt](https://github.com/cyanobacterium/PowerAdvantageAPI/files/185422/crash-2016-03-22_20.54.42-server.txt)

I go fast enough that it's all kind of a blur, so I can't remember exactly how I did this. I was in the process of laying some conveyors behind some chests, and I think the crash happened after I placed a chest that seemed like it was colliding with me or something, because I saw a brief bit of forced movement of my model, then the logout. This crash also re-occurs every time I log in.

I made a few feeble tries at fixing this, but they all failed. Time to see what kind of edits I can make to the relevant state before logging in, to maybe work around this.

**Comment by dreness** [comment]
Fixed it with [MCEdit](http://khroki.github.io/MCEdit-Unified/)!

Here's a view of the offending block:
https://youtu.be/6b2dFM42CxE

I deleted it, now I can log in again.

![2016-03-23_03 38 50](https://cloud.githubusercontent.com/assets/5242016/13982771/26025da8-f0a9-11e5-82cc-45c3ec9d27ab.png)

**Comment by DrPlantabyte** [comment]
It looks like a conveyor encountered a chest block without a tile entity. I didn't know that was possible, but clearly I'll need to add another safeguard.

**Comment by dreness** [comment]
I preserved a copy of the broken world so I can test a fix when available. I realized shortly after posting the above screenshot that the left-most conveyor is pointing the wrong way - not sure if it contributes to the problem though. Also there should have been nothing running through the conveyors or hoppers at the time of the crash.

**Comment by DrPlantabyte** [comment]
The orientation doesn't matter in this case. The crash report indicates that the conveyor is trying to ask a neighboring chest for its inventory but the chest doesn't have one yet. I'll have a fix soon

**Comment by DrPlantabyte** [comment]
Fixed in https://github.com/cyanobacterium/PowerAdvantageAPI/releases/tag/v1.5.4

**Comment by dreness** [comment]
Fantastic, I'll try this tonight on the backup copy of the broken world.

I really appreciate your responsiveness on these bugs, and I'm thinking about ways I can contribute something back. I have plans for a youtube video or two, and some additional info that might be appropriate on the wiki. I will let you know once I have something for review :)

**Comment by dreness** [comment]
Fix confirmed! The chest in question is a trapped chest which I (mistakenly) placed directly below some blocks, which I don't think is even really valid as I can't open the chest at all. Thanks again :)
